name: .NET

on: [ push, pull_request ]

jobs:
  build:
    name: Initialize build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore submodules
      run: git submodule sync --recursive
    
    - name: Update submodules
      run: git submodule update --init --remote --recursive
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Compile Chat.g4
      run: java -jar antlr4-csharp-4.6.6-complete.jar shell/ChatCorporaAnnotator/Data/Parsers/Suggester/Config/Chat.g4 -o shell/ChatCorporaAnnotator/Data/Parsers/Suggester -package ChatCorporaAnnotator.Data.Parsers.Suggester -Dlanguage=CSharp_v4_5 -visitor -listener
      
    - name: Build
      run: dotnet build -c ContinuousIntegration --no-restore
      
    - name: Test
      run: dotnet test --verbosity normal -c ContinuousIntegration
